apiVersion: v1
kind: Service
metadata:
  name: apisix-external
  namespace: gateway
  labels:
    app: apisix-external
    plane: data
    traffic: external
spec:
  selector:
    app: apisix-external
  ports:
    - name: http-ext
      port: 9080
      targetPort: 9080
    - name: metrics
      port: 9091
      targetPort: 9091
  type: ClusterIP   # Overridden to NodePort in local overlay
