apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: gateway
  labels:
    app: apisix
spec:
  selector:
    app: apisix
  ports:
    - name: http-ext
      port: 9080
      targetPort: 9080
    - name: http-int
      port: 9081
      targetPort: 9081
  type: ClusterIP   # Overridden to NodePort in local overlay
