apiVersion: v1
kind: Service
metadata:
  name: apisix-internal
  namespace: gateway
  labels:
    app: apisix-internal
    plane: data
    traffic: internal
spec:
  selector:
    app: apisix-internal
  ports:
    - name: http-int
      port: 9081
      targetPort: 9081
    - name: metrics
      port: 9091
      targetPort: 9091
  type: ClusterIP   # Overridden to NodePort in local overlay
