apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - job.yaml

# Generate a configmap from the directory structure, avoiding creating empty directories as keys
configMapGenerator:
  - name: apisix-external-config-data
    namespace: gateway
    files:
      - upstreams_product-service.json
      - services_product-service.json
      - routes_product-external.json
generatorOptions:
  disableNameSuffixHash: true
