apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Expose APISIX as NodePort so host machine can reach Minikube ports
  - path: patches/apisix-service-nodeport.yaml
    target:
      kind: Service
      name: apisix
      namespace: gateway
