apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # External data plane — expose public port as NodePort so host can reach Minikube
  - path: patches/apisix-external-nodeport.yaml
    target:
      kind: Service
      name: apisix-external
  - path: patches/apisix-internal-nodeport.yaml
    target:
      kind: Service
      name: apisix-internal
  - path: patches/apisix-admin-external-nodeport.yaml
    target:
      kind: Service
      name: apisix-admin-external
  - path: patches/apisix-admin-internal-nodeport.yaml
    target:
      kind: Service
      name: apisix-admin-internal
      namespace: gateway

  # Monitoring — expose Grafana as NodePort
  - path: patches/grafana-nodeport.yaml
    target:
      kind: Service
      name: grafana
      namespace: gateway
