apiVersion: v1
kind: Service
metadata:
  name: apisix-external
  namespace: gateway
spec:
  type: NodePort
  ports:
    - name: http-ext
      port: 9080
      targetPort: 9080
      nodePort: 30080   # External (public) — curl http://$(minikube ip):30080/...
