apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: gateway
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus.gateway.svc.cluster.local:9090
        isDefault: true
        editable: true
